#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Linting, testing and building your project before committing'

yarn lint-staged

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'